### ISSUE TITLE
Fix remote exec nodes controller reconcillation

### ISSUE THREAD

**Issue by l0kix2** [ytsaurus/yt-k8s-operator#263]
Currently at least deleted sts is not detected as @kruftik reported

**Comment by zlobober** [comment]
@kruftik, could you please provide some minimal reproduce?

**Comment by kruftik** [comment]
well, just remove STS and see whether it'll be recreated?:)

**Comment by kruftik** [comment]
besides that, I believe any modifications in remoteexecnode custom resource don't get applied to generated resource manifests / configs

**Comment by kruftik** [comment]
# repro:

* create an ytsaurus cluster by any means

* Create a RemoteYtsurus custom resource instance

something like

```yaml
apiVersion: cluster.ytsaurus.tech/v1
kind: RemoteYtsaurus
metadata:
  name: yt
  namespace: default
spec:
  cellTag: <actualCellTagDecimalNumber>
  cellTagMasterCaches: <actualCellTagDecimalNumber>

  hostAddresses: [ <list-of-yt-primary-master-hostnames> ]
```

* and RemoteExecNodes instance

something like

```yaml
apiVersion: cluster.ytsaurus.tech/v1
kind: RemoteExecNodes
metadata:
  name: remote
  namespace: default
spec:
  remoteClusterSpec:
    name: yt

  name: remote
  instanceCount: 1
  minReadyInstanceCount: 0

  privileged: true
  image: <exec node image label:tag>

  tolerations: []
  affinity: {}

  resources:
    requests:
      cpu: 2
      memory: 8Gi
    limits:
      cpu: 2
      memory: 8Gi

  jobResources:
    requests:
      cpu: 4
      memory: 8Gi
    limits:
      cpu: 4
      memory: 8Gi

  tags: [ "rack:fake" ]
  rack: "fake"

  volumes: []

  locations:
    - locationType: ChunkCache
      path: /yt/hdd1/chunk-cache
    - locationType: ImageCache
      path: /yt/hdd1/containerd
    - locationType: Slots
      path: /yt/hdd2/slots
    - locationType: Slots
      path: /yt/hdd3/slots
    - locationType: Logs
      path: /yt/exec-node-logs

  jobEnvironment:
    userSlots: 10
    cri:
      sandboxImage: "registry.k8s.io/pause:3.9"
      apiRetryTimeoutSeconds: 1800
    isolated: false
```

* apply them and wait for corresponding statefuleset and pods appeared

I didn't dig into the details too deep but according to

```
2024-09-04T16:32:54.961Z	INFO	Setting status for remote exec nodes	{"controller": "remoteexecnodes", "controllerGroup": "cluster.ytsaurus.tech", "controllerKind": "RemoteExecNodes", "RemoteExecNodes": {"name":"xxx","namespace":"xxx"}, "namespace": "xxx", "name": "xxx", "reconcileID": "some-id", "component": "remoteexecnodes", "status": "Running"}
```

in the operator logs, it seems it considers the node group to be healthy and in the desired state.

then, you can try to

* remove STS resource in k8s cluster to ensure it won't be recreated during the next reconciliation loop iteration (sts recreation is the expected behaviour)
* remove k8s configmap\service\something else to check whether it's the sts specific issuer or a general one (recreation of the related resources is the expected behaviour)
* change iamge field value in remoteexecnode resource specification. the expected behaviour - the operator scales down the existing sts, changes the image and scales it up again to the desired one
