### ISSUE TITLE
setting nodePort

### ISSUE THREAD

**Issue by uvrds** [ytsaurus/yt-k8s-operator#44]
setting node port for all components via configuration file
For example: 
```
httpProxies:
  - serviceType: NodePort
    instanceCount: 3
    nodePort: 31860 - setting
```
when I apply config I got error: 
**strict decoding error: unknown field "spec.httpProxies[0].nodePort", unknown field "spec.rpcProxies[0].nodePort"**
